# fly.toml file generated for nexus-service on 2022-11-12T11:35:07+01:00

app = "nexus-service"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

	[[services.http_checks]]
		path = "/health"
		method = "get"
		port = 3000
		protocol = "http"
		interval = "10s"
		timeout = "2s"
		grace_period = "1s"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

