name: Deploy
on:
  push:
    branches: [main]
    paths:
      - '**.go'
      - Dockerfile

jobs:
  deploy:
    name: Push to fly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: fly deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
