# This is a basic workflow to help you get started with Actions

name: Build and deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch: {}
  push:
    branches:
    - main
    paths:
      - '*/**.go'
      - Dockerfile

      # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Github Tag Bump
        id: bump_version
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main
          WITH_V: true

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "image_registry=ghcr.io/oslokommune" >> $GITHUB_ENV
      - run: echo "image_name=bordtennis-nexus-service" >> $GITHUB_ENV
      - run: echo "image_version=$(git tag | sort -V | tail -1)" >> $GITHUB_ENV
      - run: echo "image_uri=${{ env.image_registry }}/${{ env.image_name}}:${{ env.image_version}}" >> $GITHUB_ENV

      - name: Build and push Docker images
        run: docker build --tag ${{ env.image_uri }} .

      - name: Push docker image
        run: docker push ${{ env.image_uri }}
